name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: never

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      run: cargo build --verbose --features random
    - name: Run tests
      run: cargo test --verbose
      run: cargo test --verbose --features random
